# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_background_generator_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BackgroundGeneratorDialog(object):
    def setupUi(self, BackgroundGeneratorDialog):
        BackgroundGeneratorDialog.setObjectName("BackgroundGeneratorDialog")
        BackgroundGeneratorDialog.resize(1115, 533)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BackgroundGeneratorDialog.sizePolicy().hasHeightForWidth())
        BackgroundGeneratorDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(BackgroundGeneratorDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputGraphicsView = QtWidgets.QGraphicsView(BackgroundGeneratorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputGraphicsView.sizePolicy().hasHeightForWidth())
        self.inputGraphicsView.setSizePolicy(sizePolicy)
        self.inputGraphicsView.setObjectName("inputGraphicsView")
        self.horizontalLayout_2.addWidget(self.inputGraphicsView)
        self.outputGraphicsView = QtWidgets.QGraphicsView(BackgroundGeneratorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputGraphicsView.sizePolicy().hasHeightForWidth())
        self.outputGraphicsView.setSizePolicy(sizePolicy)
        self.outputGraphicsView.setObjectName("outputGraphicsView")
        self.horizontalLayout_2.addWidget(self.outputGraphicsView)
        self.groupBox = QtWidgets.QGroupBox(BackgroundGeneratorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.generateButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateButton.sizePolicy().hasHeightForWidth())
        self.generateButton.setSizePolicy(sizePolicy)
        self.generateButton.setObjectName("generateButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.generateButton)
        self.strideSpinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strideSpinBox.sizePolicy().hasHeightForWidth())
        self.strideSpinBox.setSizePolicy(sizePolicy)
        self.strideSpinBox.setMinimum(1)
        self.strideSpinBox.setMaximum(300)
        self.strideSpinBox.setProperty("value", 10)
        self.strideSpinBox.setObjectName("strideSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.strideSpinBox)
        self.setMaxButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setMaxButton.sizePolicy().hasHeightForWidth())
        self.setMaxButton.setSizePolicy(sizePolicy)
        self.setMaxButton.setObjectName("setMaxButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.setMaxButton)
        self.setMinButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setMinButton.sizePolicy().hasHeightForWidth())
        self.setMinButton.setSizePolicy(sizePolicy)
        self.setMinButton.setObjectName("setMinButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.setMinButton)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.videoPlaybackWidget = VideoPlaybackWidget(BackgroundGeneratorDialog)
        self.videoPlaybackWidget.setObjectName("videoPlaybackWidget")
        self.horizontalLayout.addWidget(self.videoPlaybackWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(BackgroundGeneratorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(BackgroundGeneratorDialog)
        self.buttonBox.accepted.connect(BackgroundGeneratorDialog.accept)
        self.buttonBox.rejected.connect(BackgroundGeneratorDialog.reject)
        self.setMinButton.pressed.connect(self.videoPlaybackWidget.setMinRange)
        self.setMaxButton.pressed.connect(self.videoPlaybackWidget.setMaxRange)
        QtCore.QMetaObject.connectSlotsByName(BackgroundGeneratorDialog)

    def retranslateUi(self, BackgroundGeneratorDialog):
        _translate = QtCore.QCoreApplication.translate
        BackgroundGeneratorDialog.setWindowTitle(_translate("BackgroundGeneratorDialog", "Dialog"))
        self.groupBox.setTitle(_translate("BackgroundGeneratorDialog", "Options"))
        self.label.setText(_translate("BackgroundGeneratorDialog", "Frame:"))
        self.generateButton.setText(_translate("BackgroundGeneratorDialog", "Generate"))
        self.setMaxButton.setText(_translate("BackgroundGeneratorDialog", "Set Max"))
        self.setMinButton.setText(_translate("BackgroundGeneratorDialog", "Set Min"))

try:
    from .video_playback_widget import VideoPlaybackWidget
except ImportError:
    from video_playback_widget import VideoPlaybackWidget
